### ISSUE TITLE
Set composer's minimum-stability to "stable"

### ISSUE THREAD

**Issue by hector-del-rio** [yii-dream-team/yii2-upload-behavior#10]

**Comment by russianlagman** [comment]
What for? :-)

**Comment by hector-del-rio** [comment]
[My composer package](hector-del-rio/yii2-image-up) depends on yours and that means that people who wants to install my/your package needs to set minimum-stability to dev.

Anyway it seems it is working wuite well, isn't it? :D

**Comment by russianlagman** [comment]
behavior package now has a stable release, so you can use it in stable packages :-)
