### ISSUE TITLE
ActiveRecord is saved even when Exception is thrown

### ISSUE THREAD

**Issue by vercotux** [yii-dream-team/yii2-upload-behavior#15]
The one thing this wonderful behavior is missing is the ability to reverse a _save_ transaction in case the file fails to be stored (for example when the system throws an Exception due to incorrect permissions). Currently what appears to happen is there is an Exception thrown but the record gets stored in the database anyway without the file.

**Comment by BioSin** [comment]
@vercotux In this case you need to use DB transactions (just for example):
```
if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $dbTransaction = Yii::$app->db->beginTransaction();
            try {
                $model->save();
                $dbTransaction->commit();
            } catch (\Exception $e) {
                $dbTransaction->rollBack();
                throw $e;
            }
            return $this->refresh();
        }
```

PS: Sorry for a loooong reply :)

**Comment by vercotux** [comment]
You expect every programmer to do this? This should be done inside the behavior.

**Comment by russianlagman** [comment]
@vercotux I think you could just add OP_INSERT/OP_UPDATE to your model transactions() method
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecord.php#L383

**Comment by vercotux** [comment]
@russianlagman What, every time I use this behavior? Are you kidding me?

The only solution here is to fork the project into my own repository and fix it to use transactions.

**Comment by russianlagman** [comment]
@vercotux you need to learn learn how to use transactional operations with scenarios: http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#transactional-operations

**Comment by vercotux** [comment]
I told you I know how to do it. Read my message again.

**Comment by russianlagman** [comment]
You should understand that not every ActiveRecord implementation could use transactions. For example, it just wont work for MyISAM, ElasticSearch connections.

**Comment by BioSin** [comment]
@vercotux  model saving with file loading is a a complex operation:
1. Save the model
2. Upload a file

Behavior shouldn't manage failures in this case because may have other operations in chain and etc. Only developer should decide how it should be handled.
Behavior doing only one thing - file uploading, all the rest should be handled by the developer depending on environment, used DB, logic, etc.

If you want, you may extend behavior and override afterSave method in your project.

**Comment by vercotux** [comment]
You should not be using this behavior with a non-transactional DBMS. Unless you *want* it to fail.

It may be complex, but this behavior needs to take care of it.
It most certainly should handle its own failures. You cannot expect that from the developer who has no understanding of how your behavior works internally.

It is *not* the developer's responsibility to handle your internal exceptions, especially when your documentation does not even warn them about it.

**Comment by russianlagman** [comment]
@vercotux please consider the situation when you need to process multiple models in a one transaction. Not all RDBMS support nested transactions. So it's up to you how to wrap saving into transaction: using transactions() or with a try/catch block (and how to handle exceptions). Documentation patches are welcome.

**Comment by vercotux** [comment]
@russianlagman Again, WHY would you be doing this on a non-transactional RDBMS? You want it to crash?
