### ISSUE TITLE
В базу сохраняет оригинальное имя, не смотря нанастройки

### ISSUE THREAD

**Issue by SlimSavernake** [yii-dream-team/yii2-upload-behavior#19]
```
            'photo' => [
                'class' => '\yiidreamteam\upload\FileUploadBehavior',
                'attribute' => 'photo1',
                'filePath' => '@webroot/upload/realty/photo1_[[pk]].[[extension]]',
                'fileUrl' => '@web/upload/realty/photo1_[[pk]].[[extension]]',
            ],
```

Сами файлы переименовываются, но в БД сохраняется оригинальное имя файла

**Comment by russianlagman** [comment]
так и должно быть

**Comment by SlimSavernake** [comment]
как переименовывать имя и в базе? они ведь должны быть одинаковые, иначе как я буду искать нужное изображение

**Comment by russianlagman** [comment]
способы получения путей и url изображения описаны в документации

**Comment by BumbuKhan** [comment]
@SlimSavernake у Вас получилось переименовать? 
Cтолкнулся с той же проблемой...

@russianlagman Вы это имеете в виду?

`$model->fileUpload = $model->getUploadedFileUrl('fileUpload');`
`$model->save()`

с методом `getUploadedFileUrl()` все ОК, но вот в атрибут модельки не записывается ничего...

**Comment by SlimSavernake** [comment]
Нет. мне сказали так и должно быть, значит так и должно быть.
Использую https://github.com/mohorev/yii2-upload-behavior
