### ISSUE TITLE
Argument 1 passed to yiidreamteam\upload\FileUploadBehavior::getInstance() must be an instance of yii\db\ActiveRecord

### ISSUE THREAD

**Issue by timmy78** [yii-dream-team/yii2-upload-behavior#25]
Hi

My model extends a custom ActiveRecord that extends BaseActiveRecord.

Or the extension only accepts a model from ActiveRecord :

Line 213 : `public static function getInstance(ActiveRecord $model, $attribute)` 

Is it possible to change it for BaseActiveRecord ?

Thanks !

**Comment by BioSin** [comment]
Hello implemented in 1.2.1 version
