### ISSUE TITLE
Missing behavior for attribute 'file'

### ISSUE THREAD

**Issue by timmy78** [yii-dream-team/yii2-upload-behavior#4]
See #3 

I have the to types of behaviors (ImageUploadBehavior & FileUploadBehavior) in my model : 
```
'image-upload' => [
    'class' => '\yiidreamteam\upload\ImageUploadBehavior',
    'attribute' => 'image',
    'filePath' => '@webroot/images/[[model]]/[[pk]]/[[basename]]',
    'fileUrl' => '@web/images/[[model]]/[[pk]]/[[basename]]',
],
'file-upload' => [
    'class' => '\yiidreamteam\upload\FileUploadBehavior',
    'attribute' => 'file',
    'filePath' => '@webroot/[[model]]/[[pk]]/[[basename]]',
    'fileUrl' => '@web/[[model]]/[[pk]]/[[basename]]',
],
```
But when want to access to my second attribute *file* with ```getUploadFilePath('file')```, it returns me an error : ```Missing behavior for attribute 'file'```. When I var_dump the current behavior class, in [FileUploadBehavior](https://github.com/yii-dream-team/yii2-upload-behavior/blob/master/src/FileUploadBehavior.php#L211), it says that *file* is an instance of *ImageUploadBehavior* which is incorrect.
When I change ```$behavior instanceof static``` to ```$behavior instanceof self``` it works.

So the problem comes when in the model _behaviors_ function the two types are declared ;)

Thank you !

**Comment by russianlagman** [comment]
thank you for your feedback, fixed!
