### ISSUE TITLE
Multi attributes : delete one image of the two images on save

### ISSUE THREAD

**Issue by timmy78** [yii-dream-team/yii2-upload-behavior#5]
I, it's again me ! :tada: 

Here my code : 
```
public function behaviors()
{
    return [
        [
            'class' => '\yiidreamteam\upload\ImageUploadBehavior',
            'attribute' => 'logo',
            'filePath' => '@webroot/images/application/[[pk]]/android_[[basename]]',
            'fileUrl' => '@web/images/application/[[pk]]/android_[[basename]]',
        ],
        [
            'class' => '\yiidreamteam\upload\ImageUploadBehavior',
            'attribute' => 'feature_graphic',
            'filePath' => '@webroot/images/application/[[pk]]/feature_graphic_[[basename]]',
            'fileUrl' => '@web/images/application/[[pk]]/feature_graphic_[[basename]]',
        ],
    ];
}
```
I have two image attributes in the same form : logo & feature-graphic

* First case : In the form, if I put the 2 files **it works** and upload the 2 images.
* Second case : I have already uploaded the "logo". But next if I put only the last file (the last declaration in the behavior, in this case "feature_graphic"), it deletes my first image (the input file is empty so it shouldn't delete it. The image is already uploaded). The image "feature_graphic" is uploaded and it is saved in DB. The attribute "logo" is not deleted in the DB that is nice.

I don't know if you need mor details or precisions ?

Thanks !

**Comment by johnb0** [comment]
I have the same problem. Someone found a solution? Thanks

**Comment by pl3xus** [comment]
Same issue here. Is there a workaround yet?
